spring:
  application:
    name: Skytel_App
  datasource:
    driver-class-name: org.h2.Driver
    password: root
    url: jdbc:h2:mem:testdb
    username: david
  jpa:
    hibernate:
      ddl-auto: update

plan-api:
  messages:
    PlanSavdSuccess: "Plan saved successfully"
    PnotSaved: "Plan not Saved"
    Pupdate: "Plan Updated Successfully"
    Pnotupdate: "Plan Not Updated "
    pDelete: "Plan Deleted Successfully"
    pNotDelete: "Plan not Deleted"
    pstatusChange: "Plan Status Changed"
    pstatusnotchange: "Plan status Not Changed"
